name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install additional dependencies
        run: |
          apt-get update
          apt-get install -y nasm grub-pc-bin grub-common make
          rustup target add x86_64-unknown-none

    - name: Run Tests
      run: make test
